#!/bin/sh
# ============================================================================================
# This unix script runs multiple numbers of scenarios on ns2 to generate trace files
# ============================================================================================
FOLDER='.'
mkdir ./TRACE

START=$(date +%s)							
COUNT=0								# Number of Created Files
X=500
Y=500
T=100								

for R in 'DSDV' 'DSR' 'AODV'							# Protocol Name
do	
  for TYPE in 'CBR' 		   				# Connection Type
  do
    for N in 50		   					# Number of Nodes
    do
      for C in 25		  				# Number of Connections
      do
	for S in 25		 				# Maximum Speed
	do
	  for P in 10						# Pause Time
	  do
	    F=1							# File Number
	    for I in 1 2 3   					# Movement Iteration Number
	    do
	      for E in 1 2 3    				# Connections Iteration Number
	      do
		  date | awk '{ print "Date: "$1" " $3 "-"$2"-"$6 }' 
		  date | awk '{ print "Time: "$4" " $5 }'  
		  echo " " 					
		  echo " " 
		  ns trace.tcl $R $TYPE $N $C $S $P $X $Y $T \
		  $FOLDER'/CONN_SCEN/'$TYPE'-N'$N'-C'$C'-E'$E \
		  $FOLDER'/MOV_SCEN/MOV-N'$N'-S'$S'-P'$P'-I'$I \
		  $FOLDER'/TRACE/'$R'-N'$N'-C'$C'-S'$S'-P'$P'-F'$F'-'$TYPE'.tr' 
		  echo "The File "$R-N$N-C$C-S$S-P$P-F$F-$TYPE.tr .... Done!!""
		  COUNT=`expr $COUNT + 1`
		  F=`expr $F + 1`
		  END=$(date +%s)
		  DIFF=$(( $END - $START ))
		  HOURS=$(( $DIFF / 3600 ))
		  MIN=$(( $DIFF / 60 ))
		  if [ "$MIN" -ge 60 ]
		  then
		    MINUTES=$(( $MIN % 60 ))
		  else
		    MINUTES=$MIN 
		  fi
		  echo "Now "$COUNT Files Done in $HOURS H:$MINUTES M""
		  echo ""
		  echo ""
		  echo ""
	      done
	    done
	  done
	done
      done
    done
  done
done

exit
